import type { Metadata } from 'next'
import { Source_Code_Pro } from 'next/font/google'
import { Analytics } from '@vercel/analytics/react';
import './globals.css'

const sourceCodePro = Source_Code_Pro({ 
  weight: '400',
  subsets: ['latin'] 
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${sourceCodePro.className} bg-black`}>{children}</body>
      <Analytics />
    </html>
  )
}
